# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "titipat achakulvisut"

# URL
url:                http://titipata.github.io
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "home"
    href:           "//titipata.github.io/"
  - name:           "about"
    href:           "//titipata.github.io/about"
  - name:           "blog"
    href:           "//titipata.github.io/blog"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
